{{- range $index := untilStep 1 (int ( add (int .Values.participantCount) 1 )) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: "terminal-service-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 7681
  selector:
    app: "terminal-{{ $index }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "external-service-3000-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 3000
  selector:
    app: "terminal-{{ $index }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "external-service-5000-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 5000
  selector:
    app: "terminal-{{ $index }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "external-service-8080-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8080
  selector:
    app: "terminal-{{ $index }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "external-service-8081-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8081
  selector:
    app: "terminal-{{ $index }}"
---
{{- end -}}
