FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  cmake \
  curl \
  g++ \
  pkg-config \
  git \
  vim-common \
  libwebsockets-dev \
  libjson-c-dev \
  libssl-dev \
  sudo \
  systemd \
  openjdk-8-jdk \
  maven \
&& rm -rf /var/lib/apt/lists/*

RUN curl -sL https://ibm.biz/idt-installer | bash
RUN git clone https://github.com/tsl0922/ttyd.git
RUN cd ttyd && mkdir build && cd build && cmake .. && make && make install

# Install instioctl
RUN curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.3.3 sh - &&\
RUN cd istio-1.3.3 &&\
RUN export PATH=$PWD/bin:$PATH

EXPOSE 7681

CMD ["ttyd", "-p", "7681", "bash"]

