FROM ubuntu:18.04

ARG ISTIO_VERSION=1.3.2
RUN mkdir /userdata

RUN apt-get update && apt-get install -y \
  cmake \
  curl \
  g++ \
  pkg-config \
  git \
  vim-common \
  libwebsockets-dev \
  libjson-c-dev \
  libssl-dev \
  sudo \
  systemd \
  wget \
&& rm -rf /var/lib/apt/lists/*

# Install ttyd terminal for web
RUN git clone https://github.com/tsl0922/ttyd.git
RUN cd ttyd && mkdir build && cd build && cmake .. && make && make install

# Install IBM Cloud Developer Tools CLI
RUN curl -sL https://ibm.biz/idt-installer | bash 
RUN ibmcloud plugin install -f -r "IBM Cloud" event-streams

# Add Node and Loopback
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs
RUN npm install -g loopback-cli

# Install instioctl and samples
WORKDIR /userdata
RUN curl -sL https://git.io/getLatestIstio | ISTIO_VERSION=$ISTIO_VERSION bash - \
  && cd ./istio-$ISTIO_VERSION \
  && cp bin/istioctl /usr/local/bin/istioctl

# Install Kafka and console tools
ADD https://www-us.apache.org/dist/kafka/2.3.0/kafka_2.12-2.3.0.tgz .
RUN tar -xvf kafka_2.12-2.3.0.tgz  
RUN rm kafka_2.12-2.3.0.tgz

EXPOSE 7681

CMD ["ttyd", "-p", "7681", "bash"]
