apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: terminal
spec:
  replicas: 20
  template:
    metadata:
      labels:
        app: terminal
    spec:
      containers:
      - name: terminal
        image: ibmappmodernization/web-terminal:0.1.1
        ports:
        - containerPort: 7681
---
apiVersion: v1
kind: Service
metadata:
  name: terminal-service
  labels:
    app: terminal
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 7681
  selector:
    app: terminal
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: terminal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - testing-cluster.us-east.containers.appdomain.cloud
    secretName: testing-cluster
  rules:
  - host: testing-cluster.us-east.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: terminal-service
          servicePort: 80
