{{- range $index := untilStep 1 (int ( add (int .Values.participantCount) 1 )) 1 }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "docker-pv-volume-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/dind-docker"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "dockervol-{{ $index }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "data-pv-volume-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/dind-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "datavol-{{ $index }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
{{- end }}