{{- range $index := untilStep 1 (int ( add (int .Values.participantCount) 1 )) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: "terminal-service-{{ $index }}"
  labels:
    app: "terminal-{{ $index }}"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 7681
  selector:
    app: "terminal-{{ $index }}"
---
{{- end -}}