# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
participantCount: 5
tlsSecret: testing-cluster
fullDomain: testing-cluster.us-east.containers.appdomain.cloud
repository: ibmappmodernization/web-terminal
tag: nodejs10
