# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
participantCount: 40
tlsSecret: clustername
fullDomain: clustername.region.containers.appdomain.cloud
repository: registry/image-name
tag: 1.0.1
